[package]
name = "chromacode"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.3.22", features = ["derive"] }
exitcode = "1.1.2"
regex = "1.9.3"
scraper = "0.17.1"
